"""initial_schema

Revision ID: 13b10b5abf97
Revises: 
Create Date: 2026-02-28 00:00:38.866444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13b10b5abf97'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('website_url', sa.String(length=500), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('onboarding', 'ingesting', 'active', 'paused', name='companystatus'), nullable=True),
    sa.Column('brand_guidelines', sa.JSON(), nullable=True),
    sa.Column('services', sa.JSON(), nullable=True),
    sa.Column('providers', sa.JSON(), nullable=True),
    sa.Column('locations', sa.JSON(), nullable=True),
    sa.Column('insurance_accepted', sa.JSON(), nullable=True),
    sa.Column('differentiators', sa.JSON(), nullable=True),
    sa.Column('target_demographics', sa.JSON(), nullable=True),
    sa.Column('competitors', sa.JSON(), nullable=True),
    sa.Column('specialty_niche', sa.String(length=500), nullable=True),
    sa.Column('existing_online_presence', sa.JSON(), nullable=True),
    sa.Column('budget_google_ads', sa.Float(), nullable=True),
    sa.Column('budget_meta_ads', sa.Float(), nullable=True),
    sa.Column('budget_email', sa.Float(), nullable=True),
    sa.Column('budget_fax', sa.Float(), nullable=True),
    sa.Column('budget_voicemail', sa.Float(), nullable=True),
    sa.Column('budget_mail', sa.Float(), nullable=True),
    sa.Column('budget_tts', sa.Float(), nullable=True),
    sa.Column('budget_social_boost', sa.Float(), nullable=True),
    sa.Column('credentials', sa.JSON(), nullable=True),
    sa.Column('posting_frequency', sa.JSON(), nullable=True),
    sa.Column('is_pilot', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('campaigns',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('external_id', sa.String(length=200), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('form_submissions', sa.Integer(), nullable=True),
    sa.Column('spend', sa.Float(), nullable=True),
    sa.Column('budget_cap', sa.Float(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_items',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('content_type', sa.Enum('blog_post', 'social_facebook', 'social_instagram', 'social_linkedin', 'ad_copy_google', 'ad_copy_meta', 'ad_creative_meta', 'fax_sheet', 'voicemail_script', 'postcard', 'email_sequence', 'directory_bio', name='contenttype'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'pending_review', 'approved', 'rejected', 'published', 'scheduled', name='contentstatus'), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('asset_url', sa.String(length=1000), nullable=True),
    sa.Column('published_url', sa.String(length=1000), nullable=True),
    sa.Column('published_at', sa.String(length=50), nullable=True),
    sa.Column('scheduled_for', sa.String(length=50), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('target_keyword', sa.String(length=300), nullable=True),
    sa.Column('meta_description', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('directory_profiles',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=100), nullable=False),
    sa.Column('profile_url', sa.String(length=500), nullable=True),
    sa.Column('is_claimed', sa.Boolean(), nullable=True),
    sa.Column('is_created', sa.Boolean(), nullable=True),
    sa.Column('completeness_score', sa.Integer(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('average_rating', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.String(length=50), nullable=True),
    sa.Column('description_short', sa.Text(), nullable=True),
    sa.Column('description_medium', sa.Text(), nullable=True),
    sa.Column('description_long', sa.Text(), nullable=True),
    sa.Column('provider_bios', sa.JSON(), nullable=True),
    sa.Column('services_listed', sa.JSON(), nullable=True),
    sa.Column('conditions_listed', sa.JSON(), nullable=True),
    sa.Column('insurance_listed', sa.JSON(), nullable=True),
    sa.Column('missing_fields', sa.JSON(), nullable=True),
    sa.Column('optimization_score', sa.Integer(), nullable=True),
    sa.Column('auto_create_status', sa.String(length=50), nullable=True),
    sa.Column('screenshot_url', sa.String(length=500), nullable=True),
    sa.Column('credentials_stored', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referral_leads',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('npi', sa.String(length=20), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('credentials', sa.String(length=50), nullable=True),
    sa.Column('specialty', sa.String(length=200), nullable=True),
    sa.Column('practice_name', sa.String(length=300), nullable=True),
    sa.Column('fax', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=300), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('new', 'contacted', 'engaged', 'referring', 'inactive', 'suppressed', name='leadstatus'), nullable=True),
    sa.Column('is_suppressed', sa.Boolean(), nullable=True),
    sa.Column('suppression_channel', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seo_reports',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=True),
    sa.Column('pagespeed_mobile', sa.Integer(), nullable=True),
    sa.Column('pagespeed_desktop', sa.Integer(), nullable=True),
    sa.Column('core_web_vitals', sa.JSON(), nullable=True),
    sa.Column('crawl_errors', sa.JSON(), nullable=True),
    sa.Column('meta_issues', sa.JSON(), nullable=True),
    sa.Column('schema_issues', sa.JSON(), nullable=True),
    sa.Column('missing_schema_types', sa.JSON(), nullable=True),
    sa.Column('ranking_keywords', sa.JSON(), nullable=True),
    sa.Column('keyword_opportunities', sa.JSON(), nullable=True),
    sa.Column('competitor_gaps', sa.JSON(), nullable=True),
    sa.Column('nap_consistency', sa.JSON(), nullable=True),
    sa.Column('gbp_score', sa.Integer(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approval_items',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('content_item_id', sa.UUID(), nullable=True),
    sa.Column('item_type', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('preview_data', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('module', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign_enrollments',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=True),
    sa.Column('next_action_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['referral_leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('touchpoints',
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Enum('email', 'fax', 'voicemail', 'mail', 'linkedin', name='touchpointchannel'), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body_preview', sa.Text(), nullable=True),
    sa.Column('external_id', sa.String(length=200), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['referral_leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('touchpoints')
    op.drop_table('campaign_enrollments')
    op.drop_table('approval_items')
    op.drop_table('seo_reports')
    op.drop_table('referral_leads')
    op.drop_table('directory_profiles')
    op.drop_table('content_items')
    op.drop_table('campaigns')
    op.drop_table('companies')
    # ### end Alembic commands ###
